### ISSUE TITLE
Failed to open .bam file error

### ISSUE THREAD

**Issue by staceyg947** [ANGSD/angsd#551] opened 2023-01-18 12:10 UTC
Hello, 

I am trying to run ANGSD to produce SFS estimations using the follow command line:

./angsd \
-bam affinis.filelist \
-doSaf 1 \
-GL 2  \
-out affinis \
-anc /path/to/fasta/file/file.fasta \
-minQ 20 \
-minMapQ 20 \
-baq 1 \
-C 50 \
 -P 4

However, it returns the following error:
[E::hts_open_format] Failed to open file /path/to/file/file_sorted.bam
angsd: multiReader.cpp:333: multiReader::multiReader(int, char**): Assertion `in' failed.

I have included the complete path to to each bam file in the list. All bam files stipulated in the list are present in the folder. 
I am using ANGSD version 0.918. 

Any advice/help would be greatly appreciated.

**Comment by isinaltinkaya** [comment] 2023-01-23 12:22
Hi,

Can you run the following commands and paste the output here?

```
file $(head -1 affinis.filelist)
samtools quickcheck -vv $(head -1 affinis.filelist)
```

Thanks,
Best,
Isin

**Comment by staceyg947** [comment] 2023-01-23 15:30
Hi @isinaltinkaya 

Thank you. 

Unfortunately, this was the output:

Loading intel version 2022.2.0
Loading intel-mkl version 2022.2.0
Loading intel-tbb version 2021.7.0
Loading intel-rt version 2022.2.0
  Load "debugger" to debug DPC++ applications with the gdb-oneapi debugger.
  Load "dpl" for additional DPC++ APIs: https://github.com/oneapi-src/oneDPL

Loading intel/2022.2.0
  Loading requirement: intel-tbb/2021.7.0 intel-rt/2022.2.0 intel-mkl/2022.2.0
/tigress/VONHOLDT/kirschel/jun22_ddRADs/2_sorted_bams/AS32041_sorted.bam
: cannot open `/tigress/VONHOLDT/kirschel/jun22_ddRADs/2_sorted_bams/AS32041_sorted.bam\015' (No such file or directory)
verbosity set to 2
/tigress/VONHOLDT/kirschel/jun22_ddRADs/2_sorted_bams/AS32041_sorted.bam
 could not be opened for reading.
/tigress/VONHOLDT/kirschel/jun22_ddRADs/2_sorted_bams/AS32041_sorted.bam

I've attached my script, the output, as well as the affinis.filelist
[angsd.zip](https://github.com/ANGSD/angsd/files/10481160/angsd.zip)

**Comment by isinaltinkaya** [comment] 2023-01-24 10:24
Hi @staceyg947,

Thank you very much for providing the files!

Unfortunately, I cannot reproduce the issue without having the actual files listed in the filelist. Would it be possible for you to create a very small subset of the data and send it?

Best wishes,
Isin

**Comment by isinaltinkaya** [comment] 2023-01-24 10:28
Hi @staceyg947,

Thank you very much for providing the files!

From what you have sent I can see that samtools also cannot access the files. Therefore I don't think this is an issue related to angsd, but an issue related to the filesystem in the servers you use. I would recommend you to get in contact with the server administrators.

Please let me know if you have other questions, 
Best wishes,
Isin

**Comment by staceyg947** [comment] 2023-01-24 13:07
Hopefully the server administrators can help me get this resolved then.

Thank you so much for your help though.

**Comment by isinaltinkaya** [comment] 2023-01-24 14:43
You're most welcome. I am closing this issue but please feel free to reopen if you experience any other issues.

Best,
Isin

**Closed by isinaltinkaya** 2023-01-24 14:43 UTC
