### ISSUE TITLE
dyld: Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv

### ISSUE THREAD

**Issue by biomendi** [ANGSD/angsd#241] opened 2019-07-31 15:09 UTC
I am following this tutorial to estimate the SFS: http://evomics.org/learning/population-and-speciation-genomics/2018-population-and-speciation-genomics/angsd-activity-sfs-fst-pbs/

The command that I am trying to execute is:

	$ANGSD -b  YRI.filelist  -anc $ANC -out yri $FILTERS $OPT -ref $REF 

where:

$ANGSD --> path to angsd program
YRI.filelist --> bam file list to African population
$ANC --> ancestral fasta file (chim)
$FILTERS --> "-minMapQ 30 -minQ 20 -minInd 8"
$OPT --> " -dosaf 1 -gl 2"
$REF --> reference genome for human

I have encountered the following error message :

```
-> angsd version: 0.929-24-gbfaa54e (htslib: 1.9-287-g53be0f9) build(Jul 30 2019 11:50:04)
dyld: lazy symbol binding failed: Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
  Referenced from: /Users/server_mac2/bioinfo_programs/angsd/angsd
  Expected in: /usr/lib/libstdc++.6.dylib

dyld: Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
  Referenced from: /Users/server_mac2/bioinfo_programs/angsd/angsd
  Expected in: /usr/lib/libstdc++.6.dylib
```
I am using a Mac (OS X 10.12). 

Any insights into this?

**Comment by biomendi** [comment] 2019-07-31 15:41
The command does work if a single bam file is provided and "-minInd" is deleted. Any idea why it does not work with a list of bam files?

**Comment by ANGSD** [comment] 2019-07-31 15:47
Its not an error ive seen before which compiler version are you using?

Den ons. 31. jul. 2019 kl. 17.41 skrev Santiago Montero-Mendieta <
notifications@github.com>:

**Comment by biomendi** [comment] 2019-07-31 16:15
Thanks for the quick reply. 

I believe the compiler is gcc (GCC) 4.8.5. 

I attach the full output of the compiling commands: 

```cd htslib;make;cd ../angsd ;make HTSSRC=../htslib```

[htslib_make.txt](https://github.com/ANGSD/angsd/files/3452884/htslib_make.txt)
[angsd_make.txt](https://github.com/ANGSD/angsd/files/3452885/angsd_make.txt)

**Comment by ANGSD** [comment] 2019-08-17 02:42
Hi I actually have no idea why this is not working. I have never seen this error, and im puzzled why it only complains for some of the parameters.

**Comment by nspope** [comment] 2019-08-17 02:59
What is operating system -- you would not happen to be on Solaris? It is suspicious that compilers are different b/w htslib and angsd ... and if so that is probably the cause of the linking issue

Nate

**Comment by ANGSD** [comment] 2020-01-09 11:07
Hi I am closing this issue, but feel free to reopen if it is still relevant.

**Closed by ANGSD** 2020-01-09 11:07 UTC
