### ISSUE TITLE
realSFS segfaults on  2D SFS (with folded input, estimated from vcfs)

### ISSUE THREAD

**Issue by dwinter** [ANGSD/angsd#70] opened 2017-02-13 22:24 UTC
Hi, I am trying to estimate a 2D SFS from _folded_ SFS estimated from likelihoods provided in a a vcf files.

Using the latest angsd (`angsd version: 0.917-33-g6d2aec8 (htslib: 1.3.2-220-g84a89da) build(Feb  9 2017 10:00:50)`, estimating the per-population sfs files seems to go fine, but `realSFS` seg faults when I try to make a 2D SFS.

```sh
gdb -ex=r --args  ~/src/angsd/misc/realSFS lbi.saf.idx si.saf.idx
```

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
	-> Version of fname:lbi.saf.idx is:2
	-> Assuming .saf.gz file: lbi.saf.gz
	-> Assuming .saf.pos.gz: lbi.saf.pos.gz
	-> Version of fname:si.saf.idx is:2
	-> Assuming .saf.gz file: si.saf.gz
	-> Assuming .saf.pos.gz: si.saf.pos.gz
	-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:(null) start:-1 stop:-1 fname:si.saf.idx fstout:(null) oldout:0 seed:1487024277 bootstrap:0 whichFst:0
	-> Multi SFS is 'still' under development. Please report strange behaviour
	-> You are printing the optimized SFS to the terminal consider dumping into a file
	-> E.g.: './realSFS lbi.saf.idx si.saf.idx >sfs.ml.txt'
	-> nSites: 35741
	-> The choice of -nSites will require atleast: 3.272186 megabyte memory, that is at least: 0.01% of total memory
	-> dim(lbi.saf.idx):10
	-> dim(si.saf.idx):10
	-> Dimension of parameter space: 100
	-> Done reading data from chromosome will prepare next chromosome
	-> Is in multi sfs, will now read data from chr:ScrUdWx_10
	-> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect 
	-> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites
	-> Sites to keep[ScrUdWx_10] from pop0:	19
	-> Sites to keep[ScrUdWx_10] from pop1:	19
	-> [readdata] lastread:19 posi:159804
	-> Comparing positions: 1 with 0 has:19
	-> Only read nSites: 19 will therefore prepare next chromosome (or exit)
	-> Done reading data from chromosome will prepare next chromosome

[SNIP many scaffolds that seem to work fine]

        -> Is in multi sfs, will now read data from chr:ScrUdWx_101
	-> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect 
	-> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites

Program received signal SIGSEGV, Segmentation fault.
0x00005555555571eb in set_intersect_pos (saf=std::vector of length 2, capacity 2 = {...}, chooseChr=0x5555557e2950 "ScrUdWx_101", start=-1, stop=-1, curChr=0x0, fl=0x0) at multisafreader.hpp:142
142		hit->d[saf[i]->ppos[j]]++;
```

Happy to send saf files if that helps.

**Comment by ANGSD** [comment] 2017-02-14 08:12
Sure, please send the saffiles. That would be very helpfull

**Comment by twooldridge** [comment] 2017-08-23 00:40
Hi, I am wondering if the cause of this problem was ever determined? I'm running into the exact same issue using angsd 0.918. Single SFS works fine, but 2d SFS produces a segfault for 2 of 24 chromosomes; Here's an example:

`gdb -ex=r --args ~/Software/angsd/misc/realSFS PO.saf.idx BW.saf.idx -r chr4:`

This produces:

```
[Thread debugging using libthread_db enabled]
	-> Version of fname:PO.saf.idx is:2
	-> Assuming .saf.gz file: PO.saf.gz
	-> Assuming .saf.pos.gz: PO.saf.pos.gz
	-> Version of fname:BW.saf.idx is:2
	-> Assuming .saf.gz file: BW.saf.gz
	-> Assuming .saf.pos.gz: BW.saf.pos.gz
	-> args: tole:0.000001 nthreads:4 maxiter:100 nsites:0 start:(null) chr:chr4 start:-1 stop:-1 fstout:(null) oldout:0 seed:1503448514 bootstrap:0 whichFst:0 fold:0 ref:(null) anc:(null)
	-> Multi SFS is 'still' under development. Please report strange behaviour
	-> You are printing the optimized SFS to the terminal consider dumping into a file
	-> E.g.: './realSFS PO.saf.idx BW.saf.idx -r chr4 >sfs.ml.txt'
	-> nSites: 5458148
	-> The choice of -nSites will require atleast: 562.171936 megabyte memory, that is at least: 3.53% of total memory
	-> dim(PO.saf.idx):11
	-> dim(BW.saf.idx):12
	-> Dimension of parameter space: 132
	-> Done reading data from chromosome will prepare next chromosome
	-> hello Im the master merge part of realSFS. and I'll now do a tripple bypass to find intersect 
	-> 1) Will set iter according to chooseChr and start and stop, and possibly using -sites

Program received signal SIGSEGV, Segmentation fault.
0x0000000000413e68 in set_intersect_pos(std::vector<persaf*, std::allocator<persaf*> >&, char*, int, int, char**, filt*) ()
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.5-7.el6_0.x86_64 glibc-2.12-1.149.el6_6.5.x86_64 libgcc-4.4.7-4.el6.x86_64 libstdc++-4.4.7-4.el6.x86_64 zlib-1.2.3-29.el6.x86_64
```

Any suggestions? The vcf files look fine for the trouble chromosmoes and validate fine using GATK's ValidateVariants.

Let me know if you need any more information. Thank you!

**Comment by ANGSD** [comment] 2019-02-22 22:18
Ok, so there was some limitations in the previous vcf reader which has now been completely rewritten.
Im closing this issue, but feel free to reopen if the problem persists in the newer version.

Best

**Closed by ANGSD** 2019-02-22 22:18 UTC
