### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ferrufa** [ANGSD/angsd#114] opened 2017-10-12 14:58 UTC
Hi,

I am fairly new to programming and ubuntu, so bear with me a bit.

When running this command as mentioned in the installation link:

cd htslib;make;cd ..

I get the following message:

gcc  -o bgzip bgzip.o libhts.a -lz -lm -lbz2 -llzma -lpthread
libhts.a(hts.o): In function `hts_hopen':
/home/fadel/htslib/hts.c:800: undefined reference to `hopen_json_redirect'
collect2: error: ld returned 1 exit status
Makefile:336: recipe for target 'bgzip' failed
make: *** [bgzip] Error 1

I have tried installing and re-installing all libraries that seemed to be related when I googled the issue and I am still getting the same message and have no idea what it is. I installed samtools, bcftools and htslib as well. Would anyone please have any suggestions?

Thanks

**Comment by ANGSD** [comment] 2017-10-12 17:14
It looks like the problem is in the compilation of htslib.
Can you try a fresh pull from github

git clone https://github.com/samtools/htslib newhtslib
cd newhtslib
make

**Comment by ferrufa** [comment] 2017-10-13 09:41
Thank you very much, seems it worked now.

I still have this warning message, but does not seem important?

prep_sites.cpp:132:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     fprintf(stderr,"\toffs:%"PRId64"\n",it->second.offs);

**Comment by ANGSD** [comment] 2017-10-18 11:28
Super, glad it worked. The warning shouldn't cause any problems. Ill close this issue, feel free to reopen if needed.

Best

**Closed by ANGSD** 2017-10-18 11:28 UTC
