### ISSUE TITLE
angsd takes up all memory

### ISSUE THREAD

**Issue by alxsimon** [ANGSD/angsd#243] opened 2019-08-04 09:46 UTC
Hi,

I am trying to understand why angsd is taking up all the memory available on my machine.

I work with 156 low coverage cram files on a machine with 48Gb of memory and a reference of around 1.4Gbases.
`angsd version: 0.929 (htslib: 1.9)`.

For example using the following command (launched through singularity and snakemake):
```
FILTERS="-uniqueOnly 1 -only_proper_pairs 1 -remove_bads 1 -skipTriallelic 1 -minMapQ {params.min_mapQ} -minQ {params.min_Q} -snp_pval {params.snp_pval} -minMaf {params.min_maf} -postCutoff {params.post_cutoff}"

TODO="-doMajorMinor 1 -doMaf 1 -doCounts 1 -dumpCounts 4 -doGlf 2 -GL 2 -doGeno 32 -doPost 1 -doVcf 1"

angsd -P {threads} -bam {input.cram} -ref {params.ref} \
-rf {input.regions} -sites {input.sites} \
-out {params.out_prefix} -setMinChunkSize 1000 \
$FILTERS $TODO
```
at first the memory usage is low, but it is slowly increasing until using everything available.
Is it the expected behaviour?

My reference have around 10 000 contigs and is ordered from the largest to the smallest.

The behaviour I expected was that once a chunk of data is read, processed and written to file, the memory should be freed, so that overall the memory usage stays constant.

Maybe I am mistaken in my understanding of how it should work. Is this a problem with the way I am using angsd?

**Comment by z0on** [comment] 2019-08-04 09:59
If your reference is in 1000s contigs, try lowering -P 
(I did have a case of angsd running out of memory on a 64G RAM machine, but I had >600 bams)

iPhone. Apologies for brevity

**Comment by alxsimon** [comment] 2019-08-04 10:03
Thank you I will try that, I forgot to say I was using -P 14.

Just to understand what is going on, does the whole reference stay in memory for each thread all along the analysis?

**Comment by z0on** [comment] 2019-08-04 17:26
I don’t really know... I just noticed that references with 1000s of contigs get processed faster with -P 1 (paradoxically), and that higher -P eats up more memory.

**Comment by ANGSD** [comment] 2019-08-17 02:39
Hi thanks for using angsd, I havent been following the issues here on github, so there has been quite some backlog. Yes there is some suboptimal design decisions in the context of many small contigs. When I wrote the filereading i was focused on fewer big chromosomes so there are quite a few flush and sleep commands when the program changes chromosomes. It is something that is on the todo list.

For most analyses it is not the cpu that is the bottleneck but the reading of the raw data, especially in the presence of many bams. -P 2, should always be faster than -P 1, since -P 2 allows for a single chunk of data to be analyses in a seperate concurrent with the filereading which is the main process that spawn the analyses threads.

With very high -Ps Ive also noticed that it us using alot of memory. The reason being that the filereading is in critical section(only one thread can write) and to make sure that the data is being printed in the proper order. Chunks of data that are done being analyses will put their data into a priority queue. If a block of the genome is much more computational intensive this priority queue will grow until it can be flushed. The issue is then if 40threads wants to put their data into the queue some racecondition could occur. This is of course also something that I should be redesigned.

Hopefully this explains what happens or what I assume is happening

Best

**Comment by alxsimon** [comment] 2019-08-17 07:04
Thank you very much for those insights, and the -P 2 trick.
That answers my questions so you can either close this issue or leave it open as a to do reminder.
Unfortunately I am not good enough in C to be of any help on those issues.
Best regards,
Alexis

**Comment by ANGSD** [comment] 2019-11-15 06:56
Dear @alxsimon , I am closing this issue.

Best

**Closed by ANGSD** 2019-11-15 06:56 UTC
