### ISSUE TITLE
problem in generating ml.file by chromosome

### ISSUE THREAD

**Issue by lee039** [ANGSD/angsd#67] opened 2017-02-01 17:16 UTC
Hello,

I'm trying to calculate Fst between two populations, using vcf files as input files.
My problem is that, ANGSD does not generate ml.file (##STEP2, see below) for chromosome 1, 2 and 14.
For the other chromosomes, it works without any problem.

Any help is greatly appreciated! :)
-------------------------------------------------------------------------------------------------
##STEP 1: loading the module
module load SHARED/angsd/0.910

##STEP 2: DOSAF for each population
#DOSAF_PYGMY##
angsd -vcf-gl /lustre/nobackup/WUR/ABGC/shared/Pig/Pygmyhog/Lim/extracting_vcf/pygmy.vcf -fai /lustre/nobackup/WUR/ABGC/shared/Pig/Sscrofa_build10_2/Ensembl72/Sus_scrofa.Sscrofa10.2.72.dna.toplevel.fa.fai -anc /lustre/nobackup/WUR/ABGC/shared/Pig/Sscrofa_build10_2/Ensembl72/Sus_scrofa.Sscrofa10.2.72.dna.toplevel.fa -r 18 -out Pygmy_vcf_chr18 -dosaf 1 -nInd 6
#DOSAF_Sus##
#angsd -vcf-gl /lustre/nobackup/WUR/ABGC/shared/Pig/Pygmyhog/Lim/extracting_vcf/non_pygmy.vcf -fai /lustre/nobackup/WUR/ABGC/shared/Pig/Sscrofa_build10_2/Ensembl72/Sus_scrofa.Sscrofa10.2.72.dna.toplevel.fa.fai -anc /lustre/nobackup/WUR/ABGC/shared/Pig/Sscrofa_build10_2/Ensembl72/Sus_scrofa.Sscrofa10.2.72.dna.toplevel.fa -r 18 -out Sus_vcf_chr18 -dosaf 1 -nInd 32

##STEP 3: Prior calculation
#2 dimension site frequency spectrum prior
#Pop1_pop2: Pygmy vs All_Sus
#/cm/shared/apps/WUR/ABGC/ANGSD/angsd0.910/misc/realSFS Pygmy_vcf_chr18.saf.idx Sus_vcf_chr18.saf.idx > Pygmy_vcf_chr18.Sus_vcf_chr18.ml

##STEP 4: Preparation for sliding window
#/cm/shared/apps/WUR/ABGC/ANGSD/angsd0.910/misc/realSFS fst index Pygmy_vcf_chr18.saf.idx Sus_vcf_chr18.saf.idx -sfs Pygmy_vcf_chr18.Sus_vcf_chr18.ml -fstout Pygmy_Sus_chr18

##STEP 5: Calculating Global Fst
#/cm/shared/apps/WUR/ABGC/ANGSD/angsd0.910/misc/realSFS fst stats Pygmy_Sus_chr18.fst.idx 

##STEP 6: Calculating Local Fst/window
#/cm/shared/apps/WUR/ABGC/ANGSD/angsd0.910/misc/realSFS fst stats2 Pygmy_Sus_chr18.fst.idx -win 50000 -step 25000 > slidingwindow_Pygmy_Sus_chr18

**Comment by ANGSD** [comment] 2017-02-08 17:59
I dont think it will be possible to track this issue down without your input files. Could it be possible to extract the data associated with chromosome1 so i can see what goes on?

Best regards

**Comment by lee039** [comment] 2017-02-09 14:10
Thanks for your comment! I'm new to Github and not sure whether I can upload my input files through comments. Otherwise can you send me an e-mail to me? then I can send you the input files. :)

Lim

**Comment by ANGSD** [comment] 2017-06-15 12:17
I think this was caused by the vcf not being sorted. Im closing this issue. Feel free to reopen if needed.

**Closed by ANGSD** 2017-06-15 12:17 UTC
