### ISSUE TITLE
Segmentition fault with latest ANGSD version

### ISSUE THREAD

**Issue by idiltac** [ANGSD/angsd#479] opened 2022-04-12 09:48 UTC
Hi. I am trying to run ANGSD on 16 bams with genomic data at 32X-48X coverage/individual to calculate the maf from diploid calling and haploid calling.
Unfortunately, when I run the command, I end up with a segmentation fault every time. Here is my ANGSD version -> angsd version: 0.937 (htslib: 1.15) build(Apr  6 2022 16:51:11)

Below is my error information and commands. I tried running the code in different threads and adding the sites option, and I got the same segmentation fault result in both and I didn't get any errors when working with low coverage bam files.

-> Printing at chr: chr4 pos:3937717 chunknumber 698800 contains 851 sites
-> Printing at chr: chr4 pos:4031288 chunknumber 698900 contains 742 sites
/tmp/slurmdnode-271//job335156/slurm_script: line 21: 191090 Segmentation fault      ${angsd}/angsd -b ${bamlist} -ref ${ref} -out GL_files/${output} -GL 1 -doMaf 1 -doMajorMinor 1 -doGeno 4 -doPost 1 -doPlink 2 -nThreads 30

-> Printing at chr: chr4 pos:3937717 chunknumber 698800 contains 851 sites
-> Printing at chr: chr4 pos:4031288 chunknumber 698900 contains 742 sites
/tmp/slurmdnode-31//job335154/slurm_script: line 21: 100572 Segmentation fault      ${angsd}/angsd -b ${bamlist} -ref ${ref} -sites ${sites} -out GL_files/${output} -GL 1 -doMaf 1 -doMajorMinor 1 -doGeno 4 -doPost 1 -doPlink 2 -nThreads 30

-> Printing at chr: chr5 pos:45332160 chunknumber 3559800 contains 254 sites
-> Printing at chr: chr5 pos:45357389 chunknumber 3559900 contains 251 sites
/tmp/slurmdnode-241//job335153/slurm_script: line 22: 150715 Segmentation fault      ${angsd}/angsd -b ${bamlist} -ref ${ref} -sites ${sites} -out HaploCall/${output} -doCounts 1 -doHaploCall 2 -nThreads 30

-> Printing at chr: chr4 pos:3937717 chunknumber 698800 contains 851 sites
-> Printing at chr: chr4 pos:4031288 chunknumber 698900 contains 742 sites
/tmp/slurmdnode-1//job335152/slurm_script: line 22: 82349 Segmentation fault      ${angsd}/angsd -b ${bamlist} -ref ${ref}  -out HaploCall/${output} -doCounts 1 -doHaploCall 2 -nThreads 30

I would be very happy if you could help me with this! 
Many thanks in advance, İdil.

**Comment by jbruxaux** [comment] 2022-04-14 12:01
Hi İdil!

Not sure it helps (I'm not part of the developing team), but my experience with this type of data is that you need a lot of memory, and a reference that is of good quality = not too fragmented.
In my case I ended up creating a concatenated reference with only 20 (fake) chromosomes, and had to use "high-memory" nodes on our cluster to make it run, but then I did not get these segmentation faults anymore.
Maybe something you can try...

**Comment by idiltac** [comment] 2022-04-15 10:31
Hi,

Thank you very much for your suggestion. I will try it.

**Comment by ANGSD** [comment] 2022-07-10 11:10
Dear all, I think the excessive amounts of memory that has been reported was caused by users allocating to many threads. I have in more recent versions capped the number of threads to 8.

I am closing this issue, but feel free to reopen if needed.

**Closed by ANGSD** 2022-07-10 11:10 UTC
