### ISSUE TITLE
Segementation fault in realSFS

### ISSUE THREAD

**Issue by zilaijuand** [ANGSD/angsd#424] opened 2021-09-12 09:05 UTC
Hi：
   I got the following error:
   realSFS small.saf.idx
   -> Version of fname:small.saf.idx is:2
   Segmentation fault (core dumped)
   
   Is this error caused by insufficient memory? My memory is 256G, and the size of small.saf.gz file is 76G.
   Thanks!

**Comment by ANGSD** [comment] 2022-02-23 09:59
Hello, it seems likely that this was caused by lack of available memory. I pushed a new version last week, that should use alot less resources. I am closing this issue, feel free to reopen if needed.

**Closed by ANGSD** 2022-02-23 09:59 UTC
