### ISSUE TITLE
-minMapQ filters for FST/PBS

### ISSUE THREAD

**Issue by gmkov** [ANGSD/angsd#292] opened 2020-03-04 09:30 UTC
Dear ANGSD developers,

I have been running ANGSD for PBS/FST analyses for about 3 years, and have always been lax about filters, with the notion that genotype likelihoods (samtools model) is good at dealing with low quality sites. I have a large number of populations/individuals, at medium low depth (~6X, 30 individuals for population).

I have noticed that removing reads with low mapping scores had a huge effect on the results (many peaks of divergence lost, even those repeatedly found across replicate clines with different population sets). This is because many of reads have mapping quality of 0 (used bwa mem, meaning the read maps to multiple locations in the genome). My question is: is it necessary to remove these reads for Fst/PBS? My understanding is that any filter that skews the SFS should be avoided, and ofcourse minMapQ does change my SFS. 

Thank you very much for developing this incredible tool. 

These are my commands:
angsd -P 6 \
-anc ${!REF} -rf $REGIONS \
-dosaf 1 -gl 1 -doCounts 1 \
-remove_bads 1  -minQ 20 -minMapQ 20 \
-setMaxDepth $MAX_DEPTH \
-b $BAM_LIST -out "$POP1"

realSFS  -P 6 "$POP1".saf.idx "$POP2".saf.idx > "$POP1"."$POP2".ml

realSFS fst index ."$POP1".saf.idx "$POP2".saf.idx "$POP3".saf.idx -sfs "$POP1"."$POP2"..ml -sfs "$POP1"."$POP3".ml -sfs "$POP2"."$POP3".ml -fstout "$POP_AREA".pbs -whichFst 1

realSFS fst stats2 "$POP_AREA".pbs.fst.idx -win $WINDOW -step $WINDOW_STEP -type 0 -whichFst 1 > "$POP_AREA".bhatiaFst.pbs.5kb.1kb.idx

**Comment by nspope** [comment] 2020-03-04 20:50
By "filter that skews the SFS", what is meant is filtering sites on the *basis* of allele frequency. Like removing those where the minor allele frequency is below some threshold. Or where the null hypothesis of being monomorphic is rejected at some level of significance.

Filtering out mapped reads that are rubbish is a good idea for pretty much any downstream analysis. It's worth pointing out that unless base quality scores are adjusted to reflect mapping quality (e.g. via BAQ), the resulting genotype likelihoods will not reflect mapping quality (thus using GL does not necessarily mitigate issues with mapping). It's hard to give a "default" for -minMapQ because different methods generate scores that aren't necessarily comparable. I work mainly with insects that have relatively compact (and non-repetitive) genomes: using bwa with short reads, 13 to 15 has been a reasonable lower bound.

**Comment by gmkov** [comment] 2020-03-10 14:39
Hi- thank you very much for your quick reply. 
I have 2 follow up questions:
1) It is then worth adjusting via -baq 2 for GL to reflect mapping quality? Would this be in addition to minMapQ?

2) From many tests I have ran, it seems that increasing the minMapQ filter lowers Fst/PBS peaks of divergence (rather than removing them, see example [here )](https://www.dropbox.com/s/m1doqn38w3etkzx/test29.33.png?dl=0)- which could indicate that the most divergent regions are the ones suffering from lower mapping qualities (due to reference bias, our reference genome is not from these populations as is fairly divergent). How would you recommend we deal with such an issue? Of course removing these highly divergent regions impacts the results and feels wrong.

Thank you.

**Comment by ANGSD** [comment] 2020-05-02 03:31
Dear @gmkov I think this is very complex question with no easy answer. Ultimately I think it depends on the quality of your assembly. I had dataset where baq was required in order to get nice looking sfs. GATK has removed the option of doing baq in the more recent versions, but this is likely to be caused by the haplotypecaller which should take into account the local indel and realignment. Im closing this issue but feel free to reopen if needed.

**Closed by ANGSD** 2020-05-02 03:31 UTC
